name: Lint

on:
  push:
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/*.yml"
      - "example/hasura/docker-compose.yaml"

jobs:
  lint:
    name: Run Go lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: "1.22"
      - name: Install dependencies
        run: |
          go get -t -v ./...
          go install ./...
      - name: Format
        run: diff -u <(echo -n) <(gofmt -d -s .)
      - name: Vet
        run: go vet ./...
      - name: Lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: latest
          only-new-issues: true
          args: --timeout=120s
